# This is the main configuration file of Synkoda Edu
#
# This file contains global configs that applied over
# the edu.synkoda.com site.
#
# This file is rarely modified, so it is good to leave this file
# alone
#
# ** Server process should be restared when changes made to this
# ** file

# Site settings
title: Synkoda Edu # Name of the Site (shows at top-bar title)
email: editor@synkoda.com
description: >
  `Synkoda Edu` is a project for writing free and open source
  tutorials, examples and references on technical subjects.
baseurl: "" # the subpath of the site, this is 'root (/)' for our site
url: "http://edu.synkoda.com" # the base hostname & protocol for your site
project_name: Edu # name of the project

# Build settings
markdown: kramdown
paginate: 6
paginate_path: /page:num/

# Sidebar Settings
global_image: images/synk.png
# This the image visible in the sidebar, post-card when no image is assigned
# for a post

# Footer settings
made_by: 
  name: synkoda
  link: 'http://synkoda.com'

# Socials
github: http://github.com/synkodr
facebook: https://facebook.com/#
forum: http://synkoda.com

gems: [jekyll-paginate, jekyll-seo-tag]
